cache: vendor
language: go
go:
  - 1.13
os:
  - linux
sudo: false
install: true
script:
  - env GO111MODULE=on go build cmd/ecs-deploy/*.go
  - env GO111MODULE=on go build cmd/ecs-client/*.go
  - env GO111MODULE=on go test -v ./...
